name: Storybook

on:
  workflows: [Main]

jobs:
    docs:
        runs-on: ubuntu-latest
        needs: [test]

        name: Deploying to surge
        steps:
          - uses: actions/checkout@v1
          - name: Install surge and fire deployment
            uses: actions/setup-node@v3
          - run: npm ci
          - run: npm run build-storybook
          - run: npm install -g surge
          - run: surge ./storybook-static ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
