# @format

name: Pull request checks

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.13
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint:ts
      - run: npm run build:pr
      - name: Publish preview social
        uses: netlify/actions/cli@master
        id: publish_preview_social
        with:
          args: deploy --dir=./dist/social_platform
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_PREVIEW_APP: true # or perhaps like this
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_PR_ID: ${{ github.pr_id }}-social
      - name: Publish preview skills
        uses: netlify/actions/cli@master
        id: publish_preview_skills
        with:
          args: deploy --dir=./dist/skills
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SKILLS_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_PREVIEW_APP: true # or perhaps like this
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_PR_ID: ${{ github.pr_id }}-skills
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Social platform url - ${{steps.publish_preview_social.outputs.NETLIFY_URL}}
            Skills platform url - ${{steps.publish_preview_skills.outputs.NETLIFY_URL}}
