name: Pull request checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.13
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: npm run build:pr
    - name: Publish preview
      uses: netlify/actions/cli@master
      id: publish_preview
      with:
        args: deploy --dir=./dist
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        NETLIFY_PREVIEW_APP: true # or perhaps like this
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_PR_ID: ${{ github.pr_id }}
    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          Social platform url - ${{steps.publish_preview.outputs.NETLIFY_URL}}/social_platform
          Skills platform url - ${{steps.publish_preview.outputs.NETLIFY_URL}}/skills
